apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-ecm-kvname
  namespace: dev-exstream
spec:
  provider: azure
  secretObjects:
  - secretName: 
    type: Opaque
    data:
    - objectName: dasdbDBUser
      key: dasdbDBUser
    - objectName: dasdbDBUserPassword
      key: dasdbDBUserPassword
    - objectName: orcdbDBUser
      key: orcdbDBUser
    - objectName: orcdbDBUserPassword
      key: orcdbDBUserPassword
    - objectName: empowerdbDBUser
      key: empowerdbDBUser
    - objectName: empowerdbDBUserPassword
      key: empowerdbDBUserPassword
    - objectName: rationalizationdbDBUser
      key: rationalizationdbDBUser
    - objectName: rationalizationdbDBUserPassword
      key: rationalizationdbDBUserPassword
    - objectName: eepdbDBUser
      key: eepdbDBUser
    - objectName: eepdbDBUserPassword
      key: eepdbDBUserPassword

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "09fba11c-0e5b-433b-bca3-b1be22723bbd"
    keyvaultName: "nsn-dev-ecm-kva-001"
    objects:  |
      array:
        - |
          objectName: dasdbDBUser
          objectType: secret
          objectVersion: ""
        - |
          objectName: dasdbDBUserPassword
          objectType: secret
          objectVersion: ""
        - |
          objectName: orcdbDBUser
          objectType: secret
          objectVersion: ""
        - |
          objectName: orcdbDBUserPassword
          objectType: secret
          objectVersion: ""
        - |
          objectName: empowerdbDBUser
          objectType: secret
          objectVersion: ""
        - |
          objectName: empowerdbDBUserPassword
          objectType: secret
          objectVersion: ""
        - |
          objectName: rationalizationdbDBUser
          objectType: secret
          objectVersion: ""
        - |
          objectName: rationalizationdbDBUserPassword
          objectType: secret
          objectVersion: ""
        - |
          objectName: eepdbDBUser
          objectType: secret
          objectVersion: ""
        - |
          objectName: eepdbDBUserPassword
          objectType: secret
          objectVersion: ""

    resourceGroup: "NSN-DEV-RGP-KVA-001"
    subscriptionId: "defff450-5812-4e47-aaec-519e6f269730"
    tenantId: "0b1d23d8-10d1-4093-8cb7-fd0bb32f81e1"
