name: deploy-helm-chart_$(Date:yyyyMMdd)$(Rev:r)

trigger: none

variables:
- group: ExperienceCloudSecrets  
- name: helmChartVersion
  value: '24.4.0'
- name: helmChartFile
  value: 'opentext-experience-cloud-$(helmChartVersion).tgz'
- name: helmValuesFile
  value: 'values.yaml'
- name: releaseName
  value: 'experience-cloud'
- name: namespace
  value: 'experience-cloud-ns'
- name: kubernetesServiceConnection
  value: 'your-k8s-service-connection'


stages:
- stage: deploy_chart
  displayName: 'Deploy Helm Chart'
  jobs:
    - job: deploy_helm_chart
      displayName: 'Deploy Helm Chart'
      pool:
        name: 'YourAgentPoolName'
      steps:
        - checkout: self
          displayName: 'Checkout Repository'

        - task: Bash@3
          displayName: 'Lint Helm Chart'
          inputs:
            targetType: 'inline'
            script: |
              helm lint $(Build.SourcesDirectory)/$(helmChartFile) -f $(Build.SourcesDirectory)/$(helmValuesFile)

        - task: HelmDeploy@0
          displayName: 'Deploy Helm Chart to AKS'
          inputs:
            connectionType: 'Kubernetes'
            kubernetesServiceConnection: '$(kubernetesServiceConnection)'
            namespace: '$(namespace)'
            command: 'upgrade'
            chartType: 'FilePath'
            chartPath: '$(Build.SourcesDirectory)/$(helmChartFile)'
            releaseName: '$(releaseName)'
            valueFile: '$(Build.SourcesDirectory)/$(helmValuesFile)'
            setValues: |
              otdsDBUser=$(DB_USER)
              otdsDBUserPassword=$(OTDS_DB_PASSWORD)

