apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-ecm-kvname
  namespace: dev-exstream
spec:
  provider: azure
  secretObjects:
  - secretName: dev-sql-password
    type: Opaque
    data:
    - objectName: dev-otds-sql-connection
      key: dev-otds-sql-connection
    - objectName: otdsDBUser
      key: otdsDBUser
    - objectName: otdsDBUserPassword
      key: otdsDBUserPassword
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "09fba11c-0e5b-433b-bca3-b1be22723bbd"
    keyvaultName: "nsn-dev-ecm-kva-001"
    objects:  |
      array:
        - |
          objectName: dev-otds-sql-connection
          objectType: secret
          objectVersion: ""
        - |
          objectName: otdsDBUser
          objectType: secret
          objectVersion: ""
        - |
          objectName: otdsDBUserPassword
          objectType: secret
          objectVersion: ""
    resourceGroup: "NSN-DEV-RGP-KVA-001"
    subscriptionId: "defff450-5812-4e47-aaec-519e6f269730"
    tenantId: "0b1d23d8-10d1-4093-8cb7-fd0bb32f81e1"
