trigger:
- none  # Adjust trigger as needed

pool:
  name: MySelfHostedPool  # Replace with your self-hosted agent pool name

variables:
  # Define the connection string directly (consider marking it as secret via the pipeline UI)
  CONNECTION_STRING: "sqlserver://nsnsqlmidev102.a51a56ea8c79.database.windows.net:1433;databaseName=ECM_OT;encrypt=true;trust"

steps:
- task: Bash@3
  displayName: "Execute SQL Scripts"
  inputs:
    filePath: "scripts/run_sql_scripts.sh"  # Path to your Bash script in the repo
  env:
    CONNECTION_STRING: $(CONNECTION_STRING)
